### PR TITLE
Added licenses to modules and fixed up the whole repository

### PR DESCRIPTION
**Pull request by PokeEngineer**
I allowed edits from maintainers for this PR because I need you to do something. All I need you to do is put the reason why extremetuxracer.sh was put in here in the spot where the three question marks are in the README file.

### CODE REVIEW

**Comment by zerojay** [comment]
It's been too long for me to remember right now. Thanks for the pull request.

**Comment by PokeEngineer** [comment]
Sure.

**Comment by PokeEngineer** [comment]
Glad to see you back!

**Comment by zerojay** [comment]
Thanks, just hadn't had a working pi in so long and just was working on getting a Retropie setup just right. Back to work. :)

**Pull request merged**
